const colors = {
  light: {
    text: '#0F172A',
    tint: '#1A56DB',
    background: '#F0F4FF',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#1A56DB',
    primaryForeground: '#FFFFFF',
    secondary: '#EFF6FF',
    secondaryForeground: '#1E40AF',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#DBEAFE',
    accentForeground: '#1E40AF',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
  },
  dark: {
    text: '#F8FAFC',
    tint: '#60A5FA',
    background: '#0B1120',
    foreground: '#F8FAFC',
    card: '#1A2744',
    cardForeground: '#F8FAFC',
    primary: '#3B82F6',
    primaryForeground: '#FFFFFF',
    secondary: '#1E3A5F',
    secondaryForeground: '#93C5FD',
    muted: '#1E293B',
    mutedForeground: '#94A3B8',
    accent: '#1E3A5F',
    accentForeground: '#93C5FD',
    destructive: '#EF4444',
    destructiveForeground: '#FFFFFF',
    success: '#10B981',
    successForeground: '#FFFFFF',
    warning: '#F59E0B',
    warningForeground: '#FFFFFF',
    border: '#334155',
    input: '#334155',
  },
  radius: 12,
};

export default colors;
