export type CustomerInput = {
  name: string; type: string; address: string;
  latitude: number | null; longitude: number | null; is_active: boolean;
};

// customer_type is generated by the database; only write its source field.
export function customerRecord(input: CustomerInput): CustomerInput {
  if (typeof input.name !== 'string' || typeof input.type !== 'string'
    || typeof input.address !== 'string' || !input.name.trim()
    || !input.type.trim() || !input.address.trim() || typeof input.is_active !== 'boolean') {
    throw new Error('أدخل اسم العميل ونوعه وعنوانه بصورة صحيحة.');
  }
  const { latitude, longitude } = input;
  if ((latitude === null) !== (longitude === null)
    || (latitude !== null && (!Number.isFinite(latitude) || Math.abs(latitude) > 90))
    || (longitude !== null && (!Number.isFinite(longitude) || Math.abs(longitude) > 180))) {
    throw new Error('الإحداثيات غير صالحة. أدخل القيمتين معا أو اتركهما فارغتين.');
  }
  return {
    name: input.name.trim(), type: input.type.trim(), address: input.address.trim(),
    latitude, longitude, is_active: input.is_active,
  };
}
